### ISSUE TITLE
Tab bar config?

### ISSUE THREAD

**Issue by vishalbalaji** [catppuccin/kitty#13]
Is the tab bar in the screenshots just for showcasing? If not, could they please be shared?

**Comment by andreasgrafen** [comment]
It is not included with this repo as it is beyond the scope of the palette. Feel free to check my [personal config](https://github.com/andreasgrafen/dotfiles/blob/main/config/kitty/kitty.conf) for the tab bar settings tho. c:

**Comment by nekowinston** [comment]
might I suggest an improvement for the README then? would be cool if the relevant section was present in the FAQ, instead of diving through closed issues/asking again.

**Comment by vishalbalaji** [comment]
@andreasgrafen Thanks a lot for sharing the configs. I agree with @nekowinston that this could be linked in the README or maybe just the is issue for anybody that might be curious.

**Comment by andreasgrafen** [comment]
mmh, yeah. That's actually not to bad of an idea. I just would have assumed that this is self-explainatory until the question came up — my bad!
I'll add it right away. c:
