### ISSUE TITLE
Why ft=kitty?

### ISSUE THREAD

**Issue by dtomvan** [catppuccin/kitty#16]
Hi, I tried looking through your configuration for kitty and I noticed that my syntax highlighting (comments being greyed out for example) is not present in specifically and only the files in this repo. Any other kitty configuration files I have or have seen don't have this issue.

I tracked it down and it turned out to be the modeline:
```
# vim:ft=kitty
```

This didn't trigger the builtin `vim.filetype` match anymore on `*.conf` files in my Neovim, because the file type was overridden by it.

A quick side-by-side:

_With `:set ft=kitty`:_
![without the modeline, comment are not greyed out as they would](https://user-images.githubusercontent.com/51440893/218695364-09748b10-39c8-4259-b51b-ec8206e154e2.png)

_With `:set ft=conf`:
![with the modeline, greying out comments and color codes because of the # syntax for both colors and comments](https://user-images.githubusercontent.com/51440893/218695556-109bde6a-daf3-4670-bdce-f3f14f0a2677.png)

This does sadly highlight color codes incorrectly, however not having any highlighting at all is kind of intrusive, and because of this my question is: Why did you choose to add a modeline for an unknown filetype?

**Comment by dtomvan** [comment]
Ah. Alright, thank you for your explanation and sorry for bothering you

**Comment by nekowinston** [comment]
No worries, I can see how it's opinionated. But when you have a longer Kitty config, that plugin is quite nice.
