### ISSUE TITLE
[Discussion] Should the title bar color be set to the background color?

### ISSUE THREAD

**Issue by lcrownover** [catppuccin/kitty#23]
I'm wondering if the default for the value of the `macos_titlebar_color` (and `wayland_titlebar_color`) should be set to the primary background color of the theme. This way, you get a uniform look for your entire Kitty window.

Default:

<img width="826" alt="image" src="https://github.com/catppuccin/kitty/assets/15133041/74960f6f-58a5-489c-96d0-7b98d0d2f5a2">

Background color:

<img width="826" alt="image" src="https://github.com/catppuccin/kitty/assets/15133041/21e89659-c0f6-47b6-b8cc-7aa7c1a105ba">

I'm happy to toss a PR in with the changes, but I figure someone would have proposed this before and maybe there's a reason why it's not the default.

**Comment by andreasgrafen** [comment]
Yes, actually. I'm all for it. I don't see much reason not to do it. c:

**Comment by lcrownover** [comment]
Cool, I've submitted a PR 😊
