### ISSUE TITLE
Kitty theme and Neovim theme are not the same?

### ISSUE THREAD

**Issue by wantyapps** [catppuccin/kitty#3]
There is a slight difference between the themes

**Comment by wantyapps** [comment]
I think the neovim theme is correct (the color_updater.sh didn't work)

**Comment by Pocco81** [comment]
Nvim is always the first port to be updated, so yeah neovim.

> I think the neovim theme is correct (the color_updater.sh didn't work)

What exactly failed?

**Comment by wantyapps** [comment]
The background color and others are a bit off compared to the nvim one. I think it was fixed in catppuccin/kitty (pr #3)

**Comment by wantyapps** [comment]
Oops, meant #5

**Comment by WitherCubes** [comment]
Kitty follows the colors in the main repo and I think kitty has no issues.

**Comment by WitherCubes** [comment]
I guess now it follows the style guide.

**Comment by wantyapps** [comment]
I don't really know what happened to color_updater but I think it was a problem on my side. Anyway, thanks :)

**Comment by wantyapps** [comment]
And yeah, the kitty and nvim themes now match! The latest commit (?) did it all
